Map cities = {
  "EG": [
    "Alexandria Governorate",
    "Aswan Governorate",
    "Asyut Governorate",
    "Beheira Governorate",
    "Beni Suef Governorate",
    "Cairo Governorate",
    "Dakahlia Governorate",
    "Damietta Governorate",
    "Faiyum Governorate",
    "Gharbia Governorate",
    "Giza Governorate",
    "Ismailia Governorate",
    "Kafr el-Sheikh Governorate",
    "Luxor Governorate",
    "Matrouh Governorate",
    "Minya Governorate",
    "Monufia Governorate",
    "New Valley Governorate",
    "North Sinai Governorate",
    "Port Said Governorate",
    "Qalyubia Governorate",
    "Qena Governorate",
    "Red Sea Governorate",
    "Sohag Governorate",
    "South Sinai Governorate",
    "Suez Governorate"
  ],
  "SA": [
    "'Asir Region",
    "Al Bahah Region",
    "Al Jawf Region",
    "Al Madinah Region",
    "Al-Qassim Region",
    "Eastern Province",
    "Ha'il Region",
    "Jizan Region",
    "Makkah Region",
    "Najran Region",
    "Northern Borders Region",
    "Riyadh Region",
    "Tabuk Region"
  ],
  "AE": [
    "Abu Dhabi Emirate",
    "Ajman Emirate",
    "Dubai",
    "Fujairah",
    "Ras al-Khaimah",
    "Sharjah Emirate",
    "Umm al-Quwain"
  ],
  "US": [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "Baker Island",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Howland Island",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Jarvis Island",
    "Johnston Atoll",
    "Kansas",
    "Kentucky",
    "Kingman Reef",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Midway Atoll",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Navassa Island",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palmyra Atoll",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "United States Minor Outlying Islands",
    "United States Virgin Islands",
    "Utah",
    "Vermont",
    "Virginia",
    "Wake Island",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ],
};
